server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    first:
      initial-size: 1
      max-active: 5
    password: root
    url: jdbc:mysql://192.168.1.104:3306/dangao?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
  jpa:
    database: mysql

redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 5000
  pool:
  max-active: 20
  max-wait: -1
  max-idle: 8
  min-idle: 0


mybatis:
  mapper-locations: classpath*:mapper/*.xml

